apiVersion: v1
kind: Service
metadata:
  name: keypouch-web-service
  namespace: keypouch
spec:
  selector:
    app: keypouch-web
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
  type: ClusterIP
