apiVersion: v1
kind: Service
metadata:
  name: keypouch-backend-service
  namespace: keypouch
spec:
  selector:
    app: keypouch-backend
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  type: ClusterIP
